// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNTD9-q_1tqBibQ9DAvDddV7IV9u7ZNgU',
    appId: '1:466113806999:web:6b4084290a0c9d58a2dfd2',
    messagingSenderId: '466113806999',
    projectId: 'todoublevpartners',
    authDomain: 'todoublevpartners.firebaseapp.com',
    storageBucket: 'todoublevpartners.firebasestorage.app',
    measurementId: 'G-78ZXR8M3N3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOwNYIS_BO2ZHLHZyzwWG_3NszaqA-gUw',
    appId: '1:466113806999:android:77ba92edf5bb83e4a2dfd2',
    messagingSenderId: '466113806999',
    projectId: 'todoublevpartners',
    storageBucket: 'todoublevpartners.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuvMyEnHcA0TnlwqdTwSjm5MmtvNtpP1E',
    appId: '1:466113806999:ios:7779413327219419a2dfd2',
    messagingSenderId: '466113806999',
    projectId: 'todoublevpartners',
    storageBucket: 'todoublevpartners.firebasestorage.app',
    iosBundleId: 'com.example.toDoubleVPartners',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuvMyEnHcA0TnlwqdTwSjm5MmtvNtpP1E',
    appId: '1:466113806999:ios:7779413327219419a2dfd2',
    messagingSenderId: '466113806999',
    projectId: 'todoublevpartners',
    storageBucket: 'todoublevpartners.firebasestorage.app',
    iosBundleId: 'com.example.toDoubleVPartners',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNTD9-q_1tqBibQ9DAvDddV7IV9u7ZNgU',
    appId: '1:466113806999:web:532ea1a57e673f2ba2dfd2',
    messagingSenderId: '466113806999',
    projectId: 'todoublevpartners',
    authDomain: 'todoublevpartners.firebaseapp.com',
    storageBucket: 'todoublevpartners.firebasestorage.app',
    measurementId: 'G-8W9JQ2D4ZP',
  );
}
